apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: kitchen-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kitchen-api
  template:
    metadata:
      labels:
        app: kitchen-api
    spec:
      containers:
      - name: kitchen-api
        image: kitchen-api:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: PORT
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-uri
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 8
          timeoutSeconds: 3